projectdiscovery/naabu

- README.md
- pkg/runner/enumerate.go
- pkg/runner/options.go
- pkg/scan/connect.go
- pkg/scan/icmp.go
- pkg/scan/scan.go
Fixes #2 for dead hosts and added latency calculation.
> Added ping probe based check for dead + latency checks

- pkg/scan/scan.go
> switched harcoded max value to math.MaxInt32

- README.md
solving the hint about JSON output switch
> solving the hint about JSON output switch

- pkg/runner/runner.go
- pkg/scan/util.go
> added cidr support

- pkg/runner/enumerate.go
- pkg/runner/ips.go
- pkg/runner/options.go
- pkg/runner/runner.go
- pkg/scan/util.go
> added exclude ips

- cmd/naabu/tonmap.sh
> nmap helper

- go.mod
- go.sum
- pkg/runner/enumerate.go
- pkg/runner/options.go
> corrected json output

- .github/workflows/build.yaml
- .golangci.yml
- README.md
- v2/cmd/naabu/main.go
- v2/go.sum
- v2/pkg/kv/results.go
- v2/pkg/runas/runas_linux.go
- v2/pkg/runner/banners.go
- v2/pkg/runner/config.go
- v2/pkg/runner/ips.go
- v2/pkg/runner/nmap.go
- v2/pkg/runner/options.go
- v2/pkg/runner/output.go
- v2/pkg/runner/ports.go
- v2/pkg/runner/probe.go
- v2/pkg/runner/runner.go
- v2/pkg/runner/targets.go
- v2/pkg/runner/util.go
- v2/pkg/runner/validate.go
- v2/pkg/scan/externalip.go
- v2/pkg/scan/icmp.go
- v2/pkg/scan/ping.go
- v2/pkg/scan/scan.go
- v2/pkg/scan/tcpsequencer.go
- v2/pkg/scan/util.go
> Add golangci-lint to the current GitHub workflow

- v2/pkg/runner/options.go
Related https://github.com/projectdiscovery/httpx/pull/122
> Handle data from char device on stdin

- Dockerfile
Adds ca-certificates and bind-tools to Alpine final image.
> Add must-have tools to Docker image

- v2/pkg/runner/targets.go
> Supports comma separated host scanning

- .github/workflows/lint-test.yml
- v2/go.mod
- v2/pkg/runner/output.go
- v2/pkg/runner/runner.go
This PR adds support for timestamp in json output.
> timestamp for json output

- .github/workflows/lint-test.yml
- v2/cmd/naabu/main.go
- v2/go.mod
- v2/go.sum
- v2/pkg/runner/options.go
- v2/pkg/runner/resume.go
- v2/pkg/runner/runner.go
This PR adds stop/resume support.
> stop-resume support

- v2/go.mod
- v2/go.sum
- v2/pkg/runner/options.go
- v2/pkg/runner/runner.go
- v2/pkg/runner/targets.go
- v2/pkg/runner/validate.go
- v2/pkg/scan/option.go
- v2/pkg/scan/scan.go
This PR implements stream support for naabu. If enabled all other functionalities (shuffle, dedupe, resume, nmap, etc) will be disabled.
> Stream support

- README.md
- v2/pkg/runner/options.go
> portsfile mistake

- v2/cmd/functional-test/testcases.txt
This PR sets `scanme.sh` as target for functional tests
> Using scanme.sh as functional tests target

- v2/go.mod
- v2/go.sum
- v2/pkg/runner/util_test.go
This PR fixes #410 
GitHub Action OSX failed routing tracked at https://github.com/projectdiscovery/naabu/issues/412
> Fixing verify test

- README.md
- v2/pkg/result/results.go
- v2/pkg/runner/options.go
- v2/pkg/runner/runner.go
- v2/pkg/runner/validate.go
- v2/pkg/scan/option.go
- v2/pkg/scan/scan.go
example:
```console
$cat hostlist.txt | naabu -pts 5
```
will skip hosts with 5 or more than 5 ports open
> add port threshold

- v2/pkg/routing/router_darwin.go
This PR improves automatic route type detection on darwin and the error verbosity.
> Improving darwin route error verbosity + Auto route type detection

- v2/go.mod
- v2/go.sum
- v2/pkg/runner/runner.go
This PR replaces [go.uber.org/ratelimit ](url)with [projectdiscovery/ratelimit](url).
> added projectdiscovery/ratelimit

- .github/workflows/build-test.yml
- README.md
- integration_tests/run.sh
- v2/cmd/functional-test/main.go
- v2/cmd/integration-test/integration-test.go
- v2/cmd/integration-test/library.go
- v2/internal/testutils/integration.go
- v2/pkg/scan/scan.go
This PR updates the docs describing how to use naabu as a library and adds the relative integration test
> Adding library integration test

- v2/go.mod
- v2/go.sum
- v2/pkg/scan/scan.go
- v2/pkg/scan/scan_unix.go
> Fix Replace freeport with pd fork #471

- v2/pkg/runner/validate.go
This PR uses connect scan when socks proxy is provided
Closes #426
> Automatic connect scan with proxy

- v2/pkg/utils/util.go
Removed unused `MapKeysToSliceInt`
> removed utils folder

- v2/pkg/runner/runner.go
> Closing stats on exit

- v2/.goreleaser/mac.yml
- v2/.goreleaser/windows.yml
Test release - https://github.com/ehsandeep/naabu/actions/runs/4415266609
> release workflow update to build binary for more arch (mac/windows)

- .github/workflows/build-test.yml
- .github/workflows/functional-test.yml
- .github/workflows/lint-test.yml
- .github/workflows/release-binary.yml
- v2/go.mod
- v2/pkg/scan/scan.go
> Adding more coverage

- README.md
> Update README.md (small grammar change)

- v2/go.mod
- v2/go.sum
> Fix build failure on `termux`

- v2/pkg/runner/options.go
- v2/pkg/runner/runner.go
- v2/pkg/runner/validate.go
> config host discovery in `NewRunner`

- v2/pkg/runner/output.go
- v2/pkg/runner/runner.go
Closes #905
```console
go run . -list host.lst -top-ports 1000 -o result.csv -csv -cdn -exclude-cdn -scan-all-ips
```
> split port components

- v2/pkg/runner/runner.go
- v2/pkg/scan/scan.go
- v2/pkg/scan/scan_unix.go
> Cleanup interface handlers

- v2/pkg/runner/options.go
Added the `-config` parameter to customize the configuration file path
https://github.com/projectdiscovery/naabu/issues/927
> Implement flag config(#927)

- v2/pkg/runner/options.go
- v2/pkg/runner/validate.go
- v2/pkg/scan/arp_unix.go
- v2/pkg/scan/icmp.go
- v2/pkg/scan/ndp.go
- v2/pkg/scan/scan_common.go
- v2/pkg/scan/scan_unix.go
> Adding connect fallback on routing error

- v2/pkg/runner/runner.go
- v2/pkg/scan/option.go
- v2/pkg/scan/scan.go
- v2/pkg/scan/scan_common.go
- v2/pkg/scan/scan_unix.go
Closes https://github.com/projectdiscovery/aurora/issues/1070
> Disabling pcap handler with connect scan

- pkg/routing/router_freebsd.go
Hi,
Adding the file `router_freebsd.go` to fix build on FreeBSD.
> Add support to FreeBSD

- cmd/integration-test/library.go
- cmd/test/main.go
- go.mod
- go.sum
- pkg/runner/runner.go
- pkg/scan/scan.go
- pkg/utils/limits/rate.go
- pkg/utils/limits/timeout.go
- pkg/utils/timeout/timeout.go
> Larger timeout with proxy

- pkg/runner/runner.go
Close #1342
Close #1322 
input list from issue
```console
$ go run . -passive -verify -l test.txt -o port3.txt -silent | wc
40
$ wc -l test3.txt
40
```
> Fixing hosts with same ip and verify

- pkg/runner/validate.go
> Forcing syn scan with discovery

- pkg/runner/default.go
- pkg/runner/options.go
- pkg/runner/runner.go
- pkg/runner/validate.go
- pkg/runner/validate_test.go
> Fixing timeout value to connect scan default

- pkg/scan/scan_unix.go
> Fix: TCP6 Source IP bug

- pkg/runner/runner_test.go
Added comprehensive unit tests for the Runner package to improve code coverage and ensure reliability of core scanning functionality.
- `TestNewRunner`: Tests runner initialization with various configurations
- Default settings validation
- IPv6 configuration
- Custom resolver configuration
- Invalid port handling
- Progress bar functionality
- Proxy configuration
- `TestRunnerClose`: Tests proper cleanup of resources
- `TestRunnerOnReceive`: Tests result handling and callbacks
- Port result processing
- JSON/CSV output handling
- CDN detection
- IPv4/IPv6 handling
- Duplicate port handling
- `TestRunnerPickIP`: Tests IP selection from CIDR ranges
- `TestRunnerSetSourceIP`: Tests source IP configuration
- `TestRunnerSetSourcePort`: Tests source port configuration
- …
> Add Unit Tests for Runner Package

- pkg/scan/scan.go
> add missing filtering
