- pkg/runner/enumerate.go
fix error:
```
pkg/runner/enumerate.go:69: Warningf format %s reads arg #2, but call has 1 arg
```
Add hostIP to log.
> Fix log.Warningf content

- scripts/naabu2nmap.sh
I was doing recon and came across multiple hostnames that map to the same IP, so decided to change the script to resolve all hostnames to IP into a separate file.
Remove any duplicates and then only pass to NMAP.
The scripts reserves the original naabu_output_targets.txt to cross reference with IPs.
Creates a 2 new files:
-  naabu_output_ips.txt - contains all resolved IPs
- ips_to_scan.txt - All duplicate IPs removed and is the file send to NMAP.
> Resolve hostnames | Remove duplicate IPs | Pass to nmap

- Dockerfile
Hi team!
I added multi-stage build in Dockerfile for minimization.
With multi-stage build, you can reduce the amount of docker image from `933MB` to `178MB`. There was no problem when I tested it 😄
[ before ]
```
$ docker build .
$ docker images
4d216e10c92f        9 seconds ago       933MB
```
[ after ]
```
$ docker build .
$ docker images
19835a228ded        6 seconds ago        178MB
```
```
$ docker run 19835a228ded -host www.hahwul.com                                                        
__
/_//_/\_,_/\_,_/_.__/\_,_/ v2.0.2
[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Configuration file saved to …
```
> Added multi-stage build in Dockerfile for minimization.

- Dockerfile
The Dockerfile is now effectively standalone, and I've reduced the overall size by about 900MB.
> Dockerfile: swapped base for alpine to reduce footprint of image

- v2/pkg/runner/options.go
Missing closing bracket on option description of `-top-ports`
> Fixed typo

- Dockerfile
* Alpine 3.13 was released on 2021-01-14 this PR takes care of updating the Dockerfile to use Alpine 3.13
> Upgrade from Alpine 3.12 to Alpine 3.13

- .github/workflows/build.yaml
Added working directory to golangci-lint-action. The reason the lint stage was failing is because the root of the git repo contains no Golang code.
> Fix the golangci-lint stage in github actions

- Dockerfile
Docker image is using Golang 1.16, while everything else in the code is using Golang 1.15. This could lead to inconsistencies between running naabu using the Docker Image and the release artifacts.
> Fix inconsistent Golang version

- .github/workflows/build-test.yml
- .github/workflows/release-binary.yml
- Dockerfile
- v2/go.mod
- v2/go.sum
bump the project to use go1.17 and also refresh the workflow and dockerfile setup
> build: update to use go1.17

- v2/cmd/functional-test/testcases.txt
- v2/pkg/runner/ports.go
- v2/pkg/runner/ports_test.go
Minor fix for top ports options to make it simple to write/use pervasively it was a bit repetitive.
- Previously: `top-ports top-1000`
- Now: `top-ports 1000`
> Fix for top ports options

- v2/pkg/runner/options.go
- v2/pkg/runner/targets.go
- v2/pkg/runner/validate.go
- v2/pkg/runner/validate_test.go
This PR provides support for comma separated hosts.
./naabu -host yahoo.com,hackerone.com,hp.com,dell.com can be used to test this.
> support for comma separated hosts

- v2/pkg/runner/default.go
- v2/pkg/runner/options.go
- v2/pkg/runner/runner.go
This PR adds the "stats-interval/si" option, making the stats printing interval configurable (in seconds)
known `pcap` lint errors fixed in https://github.com/projectdiscovery/naabu/pull/265
> Adding customizable stats interval

- v2/go.mod
- v2/go.sum
- v2/pkg/runner/runner.go
- v2/pkg/scan/cdn.go
- v2/pkg/scan/cdn_test.go
This bumps cdncheck version in order to fix a logic bug that prevented the library to work correctly for uncached cdn cidrs.
Closes  https://github.com/projectdiscovery/cdncheck/pull/19
> Updating cdncheck

- v2/cmd/functional-test/testcases.txt
- v2/go.mod
- v2/go.sum
- v2/pkg/runner/banners.go
- v2/pkg/runner/options.go
- v2/pkg/runner/runner.go
- v2/pkg/runner/validate.go
This PR adds support for **passive** stream scan using results from [shodan internetdb](https://internetdb.shodan.io/)
```console
$ echo hackerone.com | go run . -stream -passive -verify
__
/_//_/\_,_/\_,_/_.__/\_,_/ v2.0.6
Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
[INF] Running PASSIVE scan with non root privileges
[INF] Found 10 ports on host hackerone.com (104.16.99.52)
hackerone.com:8080
hackerone.com:8443
hackerone.com:2082
hackerone.com:2086
hackerone.com:2083
hackerone.com:2087
hackerone.com:2096
hackerone.com:8880
hackerone.com:80
hackerone.com:443
```
> Adding support for passive stream scan

- v2/cmd/functional-test/testcases.txt
- v2/pkg/runner/nmap.go
- v2/pkg/runner/output_test.go
This PR groups ips in independent nmap commands according to the number of ports:
```
<100 ports
100 - 1000 ports
1000 - 10000 ports
>10000 ports
```
> Adding nmap ips grouping by range

- v2/pkg/runner/runner.go
This PR fixes redundancy in json output.
Test: naabu -l domains.txt -p 80,443 -ec -c 2 -silent -json
> added buffer reset

- v2/pkg/runner/options.go
- v2/pkg/runner/output.go
- v2/pkg/runner/output_test.go
- v2/pkg/runner/runner.go
- v2/pkg/scan/option.go
- v2/pkg/scan/scan.go
This PR adds cdn flag and displays if the IP is part of a CDN in the output.
> Issue 308 display ip part of cdn

- v2/pkg/runner/runner.go
- v2/pkg/runner/targets.go
- v2/pkg/runner/targets_test.go
This PR implements a skip scan check for IPV6 addresses
```console
$ cat targets.txt 
::ffff:c0a8:101
0:0:0:0:0:ffff:c0a8:0101
0000:0000:0000:0000:0000:ffff:c0a8:0101
192.168.1.1
$ cat targets.txt | go run . -v
...
[INF] Running CONNECT scan with non root privileges
[WRN] Skipping IPV6 address: ::ffff:c0a8:101
[WRN] Skipping IPV6 address: 0:0:0:0:0:ffff:c0a8:0101
[WRN] Skipping IPV6 address: 0000:0000:0000:0000:0000:ffff:c0a8:0101
[INF] Found 1 ports on host 192.168.1.1 (192.168.1.1)
192.168.1.1:1234
```
This will be reworked as part of https://github.com/projectdiscovery/naabu/issues/103
> Adding temporary check and skip for IPV6 addresses

- v2/go.mod
- v2/go.sum
This PR bumps `networkpolicy` version in order to fix the error described in #319 
- https://github.com/projectdiscovery/ipranger/pull/11
- https://github.com/projectdiscovery/networkpolicy/pull/10
> Fixing cidr error via networkpolicy upgrade

- v2/pkg/runner/nmap.go
- v2/pkg/runner/runner.go
- v2/pkg/runner/util.go
This PR fixes the following issues:
- Index not zeroed per blackrock iteration (Fixes #326 )
- Adds maximum length check on Windows (Fixes #316 )
Blackrock iteration:
```console
echo 192.168.1.1 | go run .
echo 192.168.1.1 | go run . -resume
```
Length Check on windows:
```console
$ echo 192.168.1.1 | go run . -tp 1000 -v -nmap-cli "nmap -o nmap.txt"
...
[INF] Running CONNECT scan with non root privileges
[INF] Found 1000 ports on host 192.168.1.1 (192.168.1.1)
192.168.1.1:443
...
[INF] Suggested nmap command: nmap -o nmap.txt -p 1,2,3,4,5,6,...,1000 192.168.1.1
```
> Fixing resume issue condition

- v2/pkg/runner/runner.go
Closes #306 
Example run - 
```console
echo hackerone.com | ./naabu  -nmap-cli 'nmap -sT' -passive 
__
/_//_/\_,_/\_,_/_.__/\_,_/ v2.0.7
Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
[INF] Running PASSIVE scan with non root privileges
[INF] Found 10 ports on host hackerone.com (104.16.100.52)
hackerone.com:8443
hackerone.com:80
hackerone.com:443
hackerone.com:2052
hackerone.com:2086
hackerone.com:2087
hackerone.com:2095
hackerone.com:2082
hackerone.com:2083
hackerone.com:8080
[INF] Running nmap command: nmap -sT -p 80,2086,8080,2087,2095,2082,2083,8443,443,2052 104.16.100.52
```
> Added nmap support to passive scan mode

- v2/pkg/runner/options.go
- v2/pkg/runner/runner.go
- v2/pkg/runner/validate.go
- v2/pkg/scan/scan.go
- v2/pkg/scan/scan_unix.go
This PR adds support for source port via the existing `source-ip` parameter
```console
$ sudo go run . -source 192.168.1.2:15000
```
> Adding source port support via source-ip

- v2/go.mod
- v2/go.sum
- v2/pkg/runner/healthcheck.go
- v2/pkg/runner/options.go
This PR implements health-check functionality
```console
$ go run . -health-check
Version: 2.0.7
Operative System: darwin
Architecture: arm64
Go Version: go1.18.2
Compiler: gc
Privileged/NET_RAW: Ok
Config file "/Users/user/.config/naabu/config.yaml" Read => Ok
Config file "/Users/user/.config/naabu/config.yaml" Write => Ok
IPv4 connectivity to scanme.sh:80 => Ko (dial tcp4 128.199.158.128:80: connect: connection refused)
IPv6 connectivity to scanme.sh:80 => Ko (dial tcp6 [2400:6180:0:d0::91:1001]:80: connect: connection refused)
```
Depends on https://github.com/projectdiscovery/goflags/pull/55
> Add health-check

- README.md
- v2/pkg/runner/options.go
- v2/pkg/runner/runner.go
- v2/pkg/scan/option.go
- v2/pkg/scan/scan.go
This PR implements support of SOCKS5 proxy authentication. 
Added `proxy-auth` option allows the user to supply a set of credentials (username:password) that may be used to authenticate against the socks5 proxy. 
In case the `proxy-auth` option is not set, the code will interact with the proxy without authentication, exactly how it worked before.
> End-to-end implementation of socks5 proxy authentication support

- v2/pkg/runner/resume.go
On Linux when the folder `/$HOME/.config/naabu/` does not exist and the user press CTRL+C `naabu` is unable to write the resume file and exit with an error.
```
$ sudo ./tools/naabu_2.0.7_linux_amd64 -l targets.txt  
[INF] Running SYN scan with CAP_NET_RAW privileges
^C[INF] CTRL+C pressed: Exiting
[INF] Creating resume file: /root/.config/naabu/resume.cfg
[ERR] Couldn't create resume file: open /root/.config/naabu/resume.cfg: no such file or directory
```
This PR fix this issue by:
* Spliting `DefaultResumeFilePath` function with a new on that return the folder only
* Creating the folder if it does not exist already
Not sure on the effect of these modifications for other operating systems.
> Fix error when config dir does not exists

- v2/pkg/scan/scan_unix.go
This PR replaceds `udp6` with privileged `ip6:icmp` which doesn't require custom ICMP configuration within linux systems
```console
$ sysctl net.ipv4.ping_group_range
net.ipv4.ping_group_range = 1   0
$ sudo go run . -host 192.168.1.1
...
192.168.1.1:80
...
```
> Replace unprivileged udp with privileged icmp

- v2/.goreleaser/windows.yml
This PR removes unstable architectures from the goreleaser workflow for windows. In detail:
- **arm+arm64** are incompatible with `https://github.com/akrylysov/pogreb` as mmap size is not defined
- **386** doesn't seem sufficiently supported/stable with the MinGW build toolchain
> Removing unstable architectures

- v2/pkg/routing/router_linux.go
Fixes #393 by replacing gopacket original slice with maps
```console
$ docker run -it ubuntu
...
192.168.1.1:80
...
```
> Fixing out of order error in gopacket linux routing

- v2/pkg/runner/validate.go
This PR fixes a wrong check with `-verify` flag what is incorrectly flagged as not supported in active scan mode
> Fixing wrong boolean check on verify condition

- Dockerfile
- v2/pkg/runner/options.go
> Skip host discovery with passive mode

- v2/pkg/runner/banners.go
- v2/pkg/runner/nmap.go
- v2/pkg/runner/util.go
- v2/pkg/runner/validate.go
`-sn` is not yet supported on windows (even though theoretically it is, since it already supports winpcap, which needs to be preinstalled on the machine, but it's not yet tested and activated). Hence this PR makes the error message more explicit
> Using osutil + improving error message with -sn on windows

- v2/pkg/runner/ports.go
- v2/pkg/runner/ports_test.go
```console
$ go run . -host 192.168.1.1 -p 80,443 -v -debug -ep 80
...
[INF] Found 1 ports on host 192.168.1.1 (192.168.1.1)
192.168.1.1:443
```
```console
$ go run . -host 192.168.1.1 -p 80 -v -debug -eh 192.168.1.1/24
...
[FTL] Could not run enumeration: no valid ipv4 or ipv6 targets were found
```
> Fixing exclude port/ip

- v2/pkg/runner/output.go
- v2/pkg/runner/output_test.go
- v2/pkg/runner/runner.go
#587 `-exclude-cdn` flag implicitly adds the CDN name to the output
> Fix excluding cdn in output with -ec flag

- README.md
- v2/pkg/runner/options.go
- v2/pkg/runner/runner.go
This PR restores the `-si` option and marks all options related to stats as deprecated, since they are exposed as json at `http://localhost:63636`
> Restoring deprecated option + readme update

- v2/pkg/runner/runner.go
- Get excuded IPs from Options
- Create a map with the IPs as key
- Only execute Host Discovery if the IP is not in the excludedIPs map.
- In Dev Branch:
- After changes :
> Fix -exclude-hosts not working when performing Only Host Discovery

- v2/pkg/port/port.go
- v2/pkg/protocol/protocol.go
- v2/pkg/runner/output.go
This pull request improves the JSON representation of the `Port` and `Protocol` fields in the `Result` struct.
Previously, the JSON output was:
```json
{
"host": "example.com",
"ip": "1.2.3.4",
"port": {"Port": 80, "Protocol": 0, "TLS": false},
"timestamp": "2023-07-06T19:48:56.838968371Z"
}
```
With the proposed changes, the JSON output will be:
```json
{
"host": "example.com",
"ip": "1.2.3.4",
"port": 80,
"protocol": "tcp",
"tls": false,
"timestamp": "2023-07-06T19:48:56.838968371Z"
}
```
This change makes the JSON output more consistent and user-friendly, by displaying Protocol as its string representation ("tcp", "udp", or "arp") and making field names in the Port struct lowercase.
> Update JSON representation of Port and Protocol

- v2/cmd/integration-test/cli.go
- v2/cmd/integration-test/integration-test.go
- v2/pkg/runner/targets.go
Closes #787.
before:
```console
$ go run . -host projectdiscovery.io -ec -silent -passive
104.26.7.152:2087
104.26.7.152:8443
104.26.7.152:8880
104.26.7.152:80
104.26.7.152:443
104.26.7.152:2082
104.26.7.152:2083
```
after:
```console
$ go run . -host projectdiscovery.io -ec -silent -passive
projectdiscovery.io:443
projectdiscovery.io:2052
projectdiscovery.io:2082
projectdiscovery.io:2083
projectdiscovery.io:2087
projectdiscovery.io:2095
projectdiscovery.io:8443
projectdiscovery.io:80
```
> fix printing issue with hostname in passive mode

- v2/pkg/runner/ips.go
- v2/pkg/runner/ips_test.go
- v2/pkg/runner/runner.go
Closes #821 
```console
$ echo www.scanme.sh | go run . -exclude-hosts scanme.sh -p 80 -verbose
__
/_//_/\_,_/\_,_/_.__/\_,_/
[INF] Current naabu version 2.1.8 (latest)
[WRN] Skipping host www.scanme.sh as ip 128.199.158.128 was excluded
[INF] Running CONNECT scan with non root privileges
[FTL] Could not run enumeration: no valid ipv4 or ipv6 targets were found
exit status 1
```
> Adding support for hostnames

- v2/pkg/privileges/privileges_freebsd.go
Closes #782 
```console
$ vagrant init generic/freebsd13
$ vagrant up
$ vagrant ssh
...
$ wget https://go.dev/dl/go1.21.4.linux-amd64.tar.gz
$ rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.4.linux-amd64.tar.gz
$ export PATH=$PATH:/usr/local/go/bin
$ go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@7bb31527659805b3865f7cae00543d41f7bdc8f6
...
github.com/projectdiscovery/naabu/v2/pkg/runner
github.com/projectdiscovery/naabu/v2/cmd/naabu
[vagrant@freebsd13 ~]$ 
```
> Adding freebsd

- .github/dependabot.yml
- .github/workflows/build-test.yml
- .github/workflows/release-test.yml
- README.md
- integration_tests/run.sh
- v2/cmd/integration-test/library.go
- v2/cmd/naabu/main.go
- v2/go.mod
- v2/pkg/result/results.go
- v2/pkg/runner/options.go
- v2/pkg/runner/resume.go
- v2/pkg/runner/runner.go
- v2/pkg/runner/targets.go
- v2/pkg/runner/util.go
- v2/pkg/runner/util_test.go
- v2/pkg/runner/validate.go
- v2/pkg/scan/arp.go
- v2/pkg/scan/arp_unix.go
- v2/pkg/scan/arp_win.go
- v2/pkg/scan/icmp.go
- v2/pkg/scan/ndp.go
- v2/pkg/scan/option.go
- v2/pkg/scan/scan.go
- v2/pkg/scan/scan_common.go
- v2/pkg/scan/scan_unix.go
- v2/pkg/scan/scan_win.go
This PR implements the following changes:
- Global pcap handler with demultiplexed pre-allocated network worker pool via source port (closes #952 and #937)
- Scan Shutdown via `context` (closes #698 )
- Adding `OnReceive` callback on response from target (partially closes #666 )
- Ipv6 is now optional (closes #914)
> Making pcap handlers shared globally

- v2/pkg/runner/runner.go
Closes #998.
before:
```console
$ go run . -host hackerone.com -top-ports 1000 -exclude-ports 80,443 -passive -v
__
/_//_/\_,_/\_,_/_.__/\_,_/
[INF] Current naabu version 2.3.0 (latest)
[INF] Running PASSIVE scan
hackerone.com:80
hackerone.com:443
hackerone.com:2053
hackerone.com:2082
hackerone.com:2083
hackerone.com:2086
hackerone.com:2087
hackerone.com:2096
hackerone.com:8080
hackerone.com:8443
hackerone.com:8880
[INF] Found 11 ports on host hackerone.com (104.18.36.214)
```
after:
```console
$ go run . -host hackerone.com -top-ports 1000 -exclude-ports 80,443 -passive -v
__
/_//_/\_,_/\_,_/_.__/\_,_/
[INF] Current naabu version 2.3.0 (latest) …
```
> fix `-exclude-ports` for `-passive`

- .github/dependabot.yml
- Dockerfile
The following vulnerabilities are fixed with alpine upgrade from 3.18.3 to 3.18.6:
- https://security.alpinelinux.org/vuln/CVE-2023-2975
- https://security.alpinelinux.org/vuln/CVE-2023-3446
- https://security.alpinelinux.org/vuln/CVE-2023-3817
- https://security.alpinelinux.org/vuln/CVE-2023-5678
- https://security.alpinelinux.org/vuln/CVE-2023-5363
> Upgrade alpine to 3.18.6 for security fixes

- v2/pkg/runner/runner.go
- v2/pkg/runner/validate.go
Closes #727 
```console
$ sudo ./naabu -p 80 -host 192.168.5.150 -debug
__
/_//_/\_,_/\_,_/_.__/\_,_/
[INF] Current naabu version 2.3.0 (latest)
[INF] Host discovery disabled: less than two ports were specified
[INF] Running SYN scan with CAP_NET_RAW privileges
192.168.5.150:80
[DBG] Received Transport (TCP) scan response from ipv4:192.168.5.150 ipv6: port:80
[INF] Found 1 ports on host 192.168.5.150 (192.168.5.150)
```
> Automatically skip redundant host discovery

- v2/pkg/scan/scan_common.go
- v2/pkg/scan/scan_unix.go
> Fixing struct initialization

- Dockerfile
Use `apk add` with `--no-cache` will prevent leaving cache in the released image, and it's now kind of Dockerfile best practice.
> Leave no apk cache in Docker image

- v2/pkg/result/confidence/confidence.go
- v2/pkg/result/results.go
Closes #1044
see repro steps at https://github.com/projectdiscovery/naabu/issues/1044
```console
$ go run . -host 183.2.172.185 -pts 2
__
/_//_/\_,_/\_,_/_.__/\_,_/
[INF] Current naabu version 2.3.0 (latest)
[INF] Running CONNECT scan with non root privileges
183.2.172.185:80
183.2.172.185:443
[INF] Skipping 183.2.172.185 [ip], Threshold reached 
[INF] Found 2 ports on host 183.2.172.185 (183.2.172.185)
[INF] Hello
```
> remove skipped check

- v2/pkg/scan/icmp.go
- v2/pkg/scan/scan_unix.go
Allow naabu to run without requiring the `net.ipv4.ping_group_range` sysctl setting or `CAP_NET_RAW` network capabilities
> making icmp non fatal

- v2/pkg/runner/runner.go
Stopping the limiter goroutine when it is no longer needed
> Fix leaking goroutine(s)

- .github/workflows/release-binary.yml
- v2/.goreleaser/linux.yml
- v2/.goreleaser/mac.yml
- v2/.goreleaser/windows.yml
`--rm-dist` was deprecated.
https://goreleaser.com/deprecations/?h=dep#-rm-dist
The release workflow failed.
https://github.com/projectdiscovery/naabu/actions/runs/11593776126/job/32278527815
```
/opt/hostedtoolcache/goreleaser-action/2.3.2/x64/goreleaser release -f .goreleaser/linux.yml --rm-dist
⨯ command failed                                   error=unknown flag: --rm-dist
Error: The process '/opt/hostedtoolcache/goreleaser-action/2.3.2/x64/goreleaser' failed with exit code 1
```
> ci(goreleaser): Fix the failure of release workflow

- pkg/runner/options.go
There was a typo saying Timeout field is in seconds. It's actually milliseconds. This confused me a lot. 
References that the value is actually interpreted as milliseconds:
* https://github.com/projectdiscovery/naabu/blob/dev/pkg/runner/options.go#L192
```go
flagSet.IntVar(&options.Timeout, "timeout", DefaultPortTimeoutSynScan, "millisecond to wait before timing out"),
```
* https://github.com/projectdiscovery/naabu/blob/dev/pkg/runner/runner.go#L117
```go
Timeout:       time.Duration(options.Timeout) * time.Millisecond,
```
> Fix units (seconds -> milliseconds) in a description of Timeout field in Options struct
